name: Build n2n-2.8.x for FreeBSD amd64

on:
  workflow_dispatch

jobs:
  build:
    runs-on: freebsd-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo pkg install -y cmake gcc gmake pkgconf

      - name: Build n2n
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
         name: n2n-binary
         path: supernode  # Replace with the path to your compiled binary or artifact
