name: Build n2n-2.8.x for FreeBSD amd64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions currently runs on Ubuntu, so we use ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build n2n-2.8.x for FreeBSD
      run: |
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
        docker buildx build --platform freebsd/amd64 -t n2n-build .
        docker run --rm n2n-build /bin/sh -c 'make'

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: n2n-binary
        path: supernode  # Replace with the path to your compiled binary or artifact
